### ISSUE TITLE
1.0 save the file -.-

### ISSUE THREAD

**Issue by d3kker** [d3kker/magic#1]
def open1():
        window.filename = filedialog.askopenfilename(initialdir="/", title="Select A File", filetypes=(("txt files", ".txt"),("all files", ".*"))) 
        **filedialog.asksaveasfile(mode='w', defaulttextsiot="2face2.txt")**

**Comment by mathiaspilch** [comment]
We don't need to save the file we opened with the file browser. Better approach (using the path to the file instead) is already in use.
